#!/usr/bin/env python3
"""Train a YOLO detector on the single-video bootstrap dataset."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MPL_DIR = PROJECT_ROOT / "model_runs" / ".matplotlib"
MPL_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(MPL_DIR))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train YOLO on the single-video end-cap dataset.")
    parser.add_argument(
        "--data",
        default="datasets/end_cap_single_video/data.yaml",
        help="YOLO data.yaml generated by prepare_single_video_yolo_dataset.py.",
    )
    parser.add_argument(
        "--model",
        default="yolov8n.pt",
        help="Initial YOLO model or local weights path.",
    )
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--device", default="", help="Examples: cpu, 0, 0,1. Empty lets Ultralytics decide.")
    parser.add_argument("--project", default="model_runs")
    parser.add_argument("--name", default="end_cap_single_video")
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument("--workers", type=int, default=2)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data_path = Path(args.data)
    if not data_path.exists():
        raise FileNotFoundError(
            f"Dataset config not found: {data_path}. Run scripts/prepare_single_video_yolo_dataset.py first."
        )

    try:
        from ultralytics import YOLO
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing dependency: ultralytics. Install project requirements first, for example: "
            "python3 -m pip install -r requirements.txt"
        ) from exc

    model = YOLO(args.model)
    train_args = {
        "data": str(data_path),
        "epochs": int(args.epochs),
        "imgsz": int(args.imgsz),
        "batch": int(args.batch),
        "project": args.project,
        "name": args.name,
        "patience": int(args.patience),
        "workers": int(args.workers),
        "exist_ok": True,
    }
    if args.device:
        train_args["device"] = args.device

    result = model.train(**train_args)
    print(result)
    print(f"best_weights={Path(args.project) / args.name / 'weights' / 'best.pt'}")


if __name__ == "__main__":
    main()
